export const data: any[] = [
  {
    id: 1,
    firstName: "Dusty",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 2,
    firstName: "Dusty 2",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 3,
    firstName: "Dusty 3",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 4,
    firstName: "Dusty 4",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 5,
    firstName: "Dusty 5",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 6,
    firstName: "Dusty 6",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 7,
    firstName: "Dusty 7",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 8,
    firstName: "Dusty 8",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 9,
    firstName: "Dusty 9",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 10,
    firstName: "Dusty 10",
    middleName: "Bayung",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    address: "261 Erdman Ford",
    city: "East Daphne",
    state: "Kentucky",
    country: "United States",
    jobTitle: "Chief Creative Technician",
  },
];
