export const data: any[] = [
  {
    id: 1,
    firstName: "Dusty",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 2,
    firstName: "Dusty 2",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 3,
    firstName: "Dusty 3",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 4,
    firstName: "Dusty 4",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 5,
    firstName: "Dusty 5",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 6,
    firstName: "Dusty 6",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 7,
    firstName: "Dusty 7",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 8,
    firstName: "Dusty 8",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 9,
    firstName: "Dusty 9",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
  {
    id: 10,
    firstName: "Dusty 10",
    lastName: "Kuvalis",
    email: "Randy63@yahoo.com",
    jobTitle: "Chief Creative Technician",
  },
];
